/**
 * The spec §3 attested-corpus SENTENCES — verbatim §3.4/§3.5-§3.9/§3.10 rows.
 *
 * Reviewer ruling (round 2): these are NOT classify()'s vocabulary. §5.1
 * assigns full test sentences to the T3/T4 `*.test.ts` files (`These tables
 * ARE the specification... becomes a vitest it.each row verbatim`, spec §3
 * preamble); `modify.ts`/`query.ts`/`help.ts` hold the GENERALIZING
 * marker/frame data those tests are classified against (spec §2.3-P2,
 * §2.5), not the sentences themselves. This file parks the full corpus so
 * it survives verbatim for T3/T4 to consume as `it.each` fixtures — nothing
 * here is imported by `classify.ts`.
 */

import type { Freq, Locale, Tier } from './types'
import type { ModifyField } from './modify'
import type { QueryIntent, QueryView } from './query'

// ===== §3.4 CONFIRM_MODIFY =====

export interface ModifyCorpusRow {
  readonly pattern: string
  readonly field: ModifyField
  readonly op?: 'remove' | 'add' | 'only'
  readonly split?: 'half' | 'everyone'
  readonly locale: Locale
  readonly tier: Tier
  readonly freq: Freq
}

export const MODIFY_CORPUS = [
  // ko main (spec §3.4 ko, 32 rows)
  {
    pattern: '3만원 말고 4만원',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '3만원이 아니라 4만원',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '3만원이 아니고 4만원',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  { pattern: '4만원', field: 'amount', locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '40000', field: 'amount', locale: 'ko', tier: 'main', freq: '상' },
  {
    pattern: '3만5천원',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '4만원으로 바꿔줘',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '민수 말고 철수',
    field: 'payer',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '민수가 아니고 철수',
    field: 'payer',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '유나가 냈어',
    field: 'payer',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '철수가 결제했어',
    field: 'payer',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '반반',
    field: 'split',
    split: 'half',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '반씩',
    field: 'split',
    split: 'half',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'n빵',
    field: 'split',
    split: 'everyone',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '엔빵',
    field: 'split',
    split: 'everyone',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '다같이',
    field: 'split',
    split: 'everyone',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '민수 빼줘',
    field: 'participants',
    op: 'remove',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: '민수 제외해줘',
    field: 'participants',
    op: 'remove',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '유나 빼고',
    field: 'participants',
    op: 'remove',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '철수도 포함',
    field: 'participants',
    op: 'add',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  { pattern: '수정', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '수정해줘', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '고쳐줘', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '바꿔줘', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '다시', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '다시 해줘', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '오타', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '오타났어', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '아 맞다', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '앗', field: null, locale: 'ko', tier: 'main', freq: '상' },
  { pattern: '그거 말고', field: null, locale: 'ko', tier: 'main', freq: '상' },
  {
    pattern: '아니 그게 아니라 4만원',
    field: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },

  // ko 확장 후보 — C-4 미검증 도메인 결합형, G-4 #3 (spec §3.4 ko 확장, 8 rows)
  {
    pattern: '금액 바꿔줘',
    field: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '중',
  },
  {
    pattern: '금액 수정해줘',
    field: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '중',
  },
  { pattern: '잘못 썼어', field: null, locale: 'ko', tier: 'exp', freq: '중' },
  {
    pattern: '잘못 입력함',
    field: null,
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  { pattern: '정정', field: null, locale: 'ko', tier: 'exp', freq: '중' },
  { pattern: '정정할게요', field: null, locale: 'ko', tier: 'exp', freq: '중' },
  { pattern: '헐 아니', field: null, locale: 'ko', tier: 'exp', freq: '하' },
  // `민수님 빼줘` — findMembers now consumes the 님/씨 honorific (goat
  // Task 4 / parser backlog #4).
  {
    pattern: '민수님 빼줘',
    field: 'participants',
    op: 'remove',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en main (spec §3.4 en, 24 rows — no en 확장 table for this intent)
  {
    pattern: 'no I meant 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'no wait I meant 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'change it to 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'change that to 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'make it 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'actually 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: "actually it's 50",
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'actually 50 not 45',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'sorry I meant 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'sorry, 50 not 45',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'scratch that, 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  { pattern: '50', field: 'amount', locale: 'en', tier: 'main', freq: '상' },
  {
    pattern: 'remove Sam',
    field: 'participants',
    op: 'remove',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'take Sam out',
    field: 'participants',
    op: 'remove',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'minus Sam',
    field: 'participants',
    op: 'remove',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'without Sam',
    field: 'participants',
    op: 'remove',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'everyone but Sam',
    field: 'participants',
    op: 'remove',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'just me and Sam',
    field: 'participants',
    op: 'only',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'split evenly',
    field: 'split',
    split: 'everyone',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: '50/50',
    field: 'split',
    split: 'half',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    pattern: 'go halves',
    field: 'split',
    split: 'half',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  { pattern: 'oops', field: null, locale: 'en', tier: 'main', freq: '중' },
  {
    pattern: 'oops meant 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    pattern: 'wait no, 50',
    field: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
] as const satisfies readonly ModifyCorpusRow[]

// ===== §3.5-§3.9 QUERY_* =====

export interface QueryCorpusRow {
  readonly input: string
  readonly intent: QueryIntent
  readonly view?: QueryView
  readonly currency?: string
  readonly locale: Locale
  readonly tier: Tier
  readonly freq: Freq
}

export const QUERY_CORPUS = [
  // ===== §3.5 QUERY_MY_BALANCE =====
  // ko main — D-1, plus F-1 붙여쓰기 / F-4 노이즈 compositions (29 rows)
  {
    input: '나 얼마 내면 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '내가 얼마 내면 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 내면 되는 거야?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 내면 되지',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 내야 돼',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '얼마 보내면 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '얼마 보내면 됨?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 얼마 보내면 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 보내야 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 정산 얼마야?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내 정산 얼마야',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내 정산 얼마 나왔어?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '정산 얼마 내면 돼',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 정산 얼마 남았어',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '정산 얼마 남았어',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 인당 얼마 내야 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '인당 얼마씩 내면 돼?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '나 1인당 얼마야?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 각 얼마씩 내는 거야',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내 몫이 얼마지',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내 몫 얼마야',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나얼마내면돼',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '얼마보내면돼',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 내면 돼??',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 내면 돼 ㅋㅋ',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '제가 얼마 내면 돼요?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '얼마 내면 되나요?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '누구한테 보내면 됨?',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '정산 누구한테 해?',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },

  // ko 확장 후보 — D-1 미검증 (7 rows)
  {
    input: '제 몫 얼마예요?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '제가 얼마 드리면 될까요?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나 얼마임?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나 얼마 냄?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나한테 청구된 금액 얼마야',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나 누구한테 돈 줘야 하지',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '이거 누구 계좌로 보내요?',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en main — D1 (16 rows)
  {
    input: 'how much do I owe',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much do i owe',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much do I owe you',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much do I owe everyone',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'what do I owe',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'what do I owe?',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'my balance',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's my balance",
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'check my balance',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's my damage",
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's the damage",
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who do I pay',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who do I owe',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who do I need to pay',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who do I venmo',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who should I venmo',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },

  // en 확장 후보 (4 rows)
  {
    input: 'am I in the red',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },
  {
    input: 'am I in the red or green',
    intent: 'QUERY_MY_BALANCE',
    view: 'amount',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },
  {
    input: 'who do I zelle',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },
  {
    input: 'zelle who',
    intent: 'QUERY_MY_BALANCE',
    view: 'who',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },

  // ===== §3.6 QUERY_PAIRWISE — requires a bound member name =====
  // ko main — D-2 (26 rows)
  {
    input: '민수가 나한테 얼마 주면 되죠?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수가 나한테 얼마 줘야 함?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수가 나한테 줄 돈 얼마야',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나는 민수한테 얼마만 주면 될 것 같은데',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '나 민수한테 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 줘야 돼?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 보내면 돼?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 받아야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 받을 돈 얼마야',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 받을 돈 있어?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 민수한테 얼마 보내야 함?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수랑 정산 얼마야',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테얼마줘야돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 줘야 돼??',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수한테 얼마 드리면 될까요?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '유나한테 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '유나한테 받을 돈 얼마야',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '유나가 나한테 얼마 주면 되죠?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '철수한테 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '철수가 나한테 얼마 줘야 함?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '철수한테 얼마 보내면 돼?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 철수한테 얼마 줘야 돼',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '민수만 아직 안 냈어?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '유나 아직 안 보냈어?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },

  // ko 확장 후보 — D-2 미검증 (3 rows)
  {
    input: '민수랑 나랑 정산 어떻게 돼?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나랑 민수 사이 얼마 남았어?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '민수님한테 얼마 줘야 돼요?',
    intent: 'QUERY_PAIRWISE',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en main — D2 (15 rows)
  {
    input: 'does Sam owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'does Sam owe me anything',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much does Sam owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'what does Sam owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'am I square with Sam',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'is Sam square with me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'settle up with Sam',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'settle with Sam',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'did Sam pay me back',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: 'has Sam paid me back yet',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: 'does Jo owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much does Jo owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'am I square with Alex',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'settle up with Alex',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much does alex owe me',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },

  // en 확장 후보 (3 rows) — no bound name (memberId: null in the spec)
  {
    input: 'are we square',
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },
  {
    input: "what's the deal with me and Sam",
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },
  {
    input: "we're square",
    intent: 'QUERY_PAIRWISE',
    locale: 'en',
    tier: 'exp',
    freq: '하',
  },

  // ===== §3.7 QUERY_GROUP_TOTAL =====
  // ko main — D-3 (25 rows)
  {
    input: '우리 총 얼마 썼어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '우리 총 얼마 썼어',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '우리총얼마썼어',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 얼마 썼어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 얼마나 썼어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 돈 얼마나 썼음',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '총 얼마 썼어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '총 얼마 나왔어',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '총 지출 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '이번 여행 총 경비 얼마야?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '이번 여행 얼마 나왔어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '이번 여행 총 지출 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '여행 경비 총 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '여행 총 얼마 나왔어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '총 경비 얼마 나왔어?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 어제 쓴 돈 총 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '정산 다 하고 나니 총 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '우리 다 합쳐서 얼마 썼어',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '다같이 쓴 돈 총 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  // '지출 내역 보여줘' MIGRATED to QUERY_HISTORY (2026-08-14): it asks for
  // the LIST, and answering with the single group total was a compromise
  // from before a list intent existed. Lives in classify.test.ts's
  // QUERY_HISTORY suite now; QueryCorpusRow's intent type has no history
  // member (history vocabulary lives in lexicons/history.ts, not
  // QUERY_MARKERS).
  {
    input: '총경비 확인해줘',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '우리 총 경비 확인해줘',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '우리 총 얼마 썼는지 보여줘',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 총 얼마 썼어??',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '우리 총 얼마 썼어 ㅋㅋ',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },

  // ko 확장 후보 — D-3 미검증 (5 rows)
  {
    input: '합계 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '다 합쳐서 얼마야',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '우리 모임 총지출 얼마예요',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '전체 지출 얼마나 돼',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '이 여행 총비용이 얼마였어요',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en main — D3 (14 rows — no en 확장 table)
  {
    input: 'how much have we spent',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much have we spent so far',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much did we spend',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much have we spent?',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's our total",
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's our total so far",
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: "what's the total",
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much has the trip cost so far',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: 'how much has this trip cost',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: 'group total',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'total for the group',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'total',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'who owes who',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'transfers',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who owes who money',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'transfers',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'who owes what',
    intent: 'QUERY_GROUP_TOTAL',
    view: 'transfers',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },

  // ===== §3.8 QUERY_MY_SPENDING =====
  // ko main — D-4 (20 rows; coverage gap declared, spec stops at 20 rather than 25)
  {
    input: '내가 낸 거 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '내가 낸 거 얼마야?',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '내가낸거얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 낸 돈 총 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '나 얼마 냈지',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 얼마 썼지',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 쓴 돈 총 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '내가 쓴 돈 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '내가 얼마 썼어?',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 결제한 거 얼마나 돼',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 결제한 거 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 이번 여행에 얼마 냈어',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 이번에 얼마 냈어',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 카드로 얼마 냈어',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '하',
  },
  {
    input: '내가 먼저 낸 돈 얼마였지',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 대신 낸 돈 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '제가 낸 거 얼마예요?',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 낸 거 얼마야 ㅋㅋ',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내가 얼마 더 낸 거야',
    intent: 'QUERY_MY_SPENDING',
    view: 'ahead',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 항목별로 얼마씩 냈지',
    intent: 'QUERY_MY_SPENDING',
    view: 'consumed',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },

  // ko 확장 후보 — D-4 미검증 (5 rows)
  {
    input: '제가 지출한 금액이 얼마예요',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '나 지출 얼마나 했어',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '내 지출 총합 보여줘',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '내 몫보다 내가 더 낸 거 얼마야',
    intent: 'QUERY_MY_SPENDING',
    view: 'ahead',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '제가 부담한 총액이 어떻게 되나요',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en main — D4 (10 rows — no en 확장 table)
  {
    input: 'how much have I spent',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much have i spent',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much have I spent?',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'what have I spent',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'my total spend',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '상',
  },
  {
    input: 'how much did I put in',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: 'how much have I paid in',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },
  {
    input: "what's my spending",
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'my spending',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'how much did i put in',
    intent: 'QUERY_MY_SPENDING',
    view: 'paid',
    locale: 'en',
    tier: 'main',
    freq: '중',
  },

  // ===== §3.9 QUERY_WALLET =====
  // ko main — D-5 (18 rows)
  {
    input: '현금 얼마 남았어?',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '현금 얼마 남았어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '현금 얼마 남았지',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '현금얼마남았어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '현금 얼마 남음?',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '남은 현금 얼마야',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '현금 얼마 있어?',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '나 현금 얼마 갖고 있지',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '지갑에 얼마 있어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '지갑에 현금 얼마 있어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '지갑 얼마 남았어?',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '내 지갑 얼마 남았어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '환전한 거 얼마 남았어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '상',
  },
  {
    input: '환전한 돈 얼마 남았어',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '남은 외화 얼마 있지',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '남은 여행 경비 얼마야',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '엔화 얼마 남았어?',
    intent: 'QUERY_WALLET',
    currency: 'JPY',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },
  {
    input: '달러 얼마 남았어',
    intent: 'QUERY_WALLET',
    currency: 'USD',
    locale: 'ko',
    tier: 'main',
    freq: '중',
  },

  // ko 확장 후보 — D-5 미검증 (4 rows)
  {
    input: '엔화 얼마 남음?',
    intent: 'QUERY_WALLET',
    currency: 'JPY',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '남은 돈 얼마 있는지 확인해줘',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '내 현금 잔액 얼마야',
    intent: 'QUERY_WALLET',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },
  {
    input: '바트 얼마 남았어',
    intent: 'QUERY_WALLET',
    currency: 'THB',
    locale: 'ko',
    tier: 'exp',
    freq: '하',
  },

  // en — coverage gap declared: 5 rows, all `low`, no 확장 table (see spec's "Coverage gaps declared")
  {
    input: 'how much cash do I have left',
    intent: 'QUERY_WALLET',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'how much cash left',
    intent: 'QUERY_WALLET',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: "what's my cash balance",
    intent: 'QUERY_WALLET',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: "what's my wallet at",
    intent: 'QUERY_WALLET',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  {
    input: 'wallet balance',
    intent: 'QUERY_WALLET',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
] as const satisfies readonly QueryCorpusRow[]

// ===== §3.10 HELP =====

export interface HelpCorpusRow {
  readonly input: string
  readonly locale: Locale
  readonly tier: Tier
  readonly freq: Freq
}

export const HELP_CORPUS = [
  // ko main — D-6. Coverage gap declared (G-4 #1: 미검증 6/16). (16 rows)
  { input: '넌 뭘 할 수 있어?', locale: 'ko', tier: 'main', freq: '상' },
  { input: '뭐 할 수 있어?', locale: 'ko', tier: 'main', freq: '상' },
  { input: '뭐 할 수 있어', locale: 'ko', tier: 'main', freq: '상' },
  { input: '뭘 할 수 있어?', locale: 'ko', tier: 'main', freq: '상' },
  { input: '뭐 할 수 있는지 알려줘', locale: 'ko', tier: 'main', freq: '중' },
  { input: '도움말', locale: 'ko', tier: 'main', freq: '상' },
  { input: '/도움말', locale: 'ko', tier: 'main', freq: '중' },
  { input: '도움말 보여줘', locale: 'ko', tier: 'main', freq: '중' },
  { input: '명령어 뭐 있어', locale: 'ko', tier: 'main', freq: '중' },
  { input: '명령어 목록 보여줘', locale: 'ko', tier: 'main', freq: '중' },
  { input: '정산 어떻게 확인해요?', locale: 'ko', tier: 'main', freq: '상' },
  { input: '이거 어떻게 쓰는 거야', locale: 'ko', tier: 'main', freq: '중' },
  { input: '어떻게 쓰는 거야?', locale: 'ko', tier: 'main', freq: '중' },
  { input: '사용법 알려줘', locale: 'ko', tier: 'main', freq: '중' },
  { input: '사용법', locale: 'ko', tier: 'main', freq: '중' },
  { input: '어떻게 써?', locale: 'ko', tier: 'main', freq: '중' },

  // ko 확장 후보 — D-6 미검증 (5 rows)
  { input: '뭐 물어보면 돼?', locale: 'ko', tier: 'exp', freq: '하' },
  { input: '사용 방법이 뭐예요', locale: 'ko', tier: 'exp', freq: '하' },
  { input: '기능 뭐 있어?', locale: 'ko', tier: 'exp', freq: '하' },
  { input: 'help', locale: 'ko', tier: 'exp', freq: '하' },
  { input: '매뉴얼 있어?', locale: 'ko', tier: 'exp', freq: '하' },

  // en — D6. Coverage gap declared (generic chatbot-onboarding material, capped at 9 rows).
  { input: 'help', locale: 'en', tier: 'main', freq: '상' },
  { input: 'help me', locale: 'en', tier: 'main', freq: '상' },
  { input: 'what can you do', locale: 'en', tier: 'main', freq: '중' },
  { input: 'what can you do?', locale: 'en', tier: 'main', freq: '중' },
  { input: 'what do you do', locale: 'en', tier: 'main', freq: '중' },
  { input: 'how do I use this', locale: 'en', tier: 'main', freq: '중' },
  { input: 'how does this work', locale: 'en', tier: 'main', freq: '중' },
  {
    input: 'what commands do you have',
    locale: 'en',
    tier: 'main',
    freq: '하',
  },
  { input: 'what can I ask you', locale: 'en', tier: 'main', freq: '하' },
] as const satisfies readonly HelpCorpusRow[]
