import { JOSA } from './lexicon-josa'
import type { SplitEntry } from '../types'

/**
 * Curated Korean verb / split lexicons.
 *
 * STEMS ONLY. Not one inflected form is written down here: 냈어/냈다/냈고/
 * 냈는데 are the stem 냈 plus `PAY_VERB_ENDING`, and 고른/먹은/만든 are a stem
 * from `VERB_STEMS_KO` plus the attributive grammar in ko/attributive.ts.
 * Enumerating the product of a lexicon and a grammar is precisely the failure
 * this branch has logged over and over (docs/SOLVED.md [2026-08-13]).
 *
 * CURATION vs MINING: the sibling `lexicon-josa`/`lexicon-decoys`/
 * `lexicon-typos` modules are GENERATED by
 * scripts/lang/mine-korean-lexicons.mjs (mecab-ko-dic + open-korean-text).
 * The tables below are hand-curated instead — mecab-ko-dic's VV.csv (동사) and
 * VA.csv (형용사) are the natural sources for `VERB_STEMS_KO` /
 * `ADJ_STEMS_KO`, but mining needs network access, which was not available in
 * the session that wrote this file. The shape is deliberately mining-ready:
 * these arrays are plain stem lists with no grammar baked in, so a future
 * `mineVerbs`/`mineAdjectives` pass can replace their CONTENTS without any
 * change to ko/attributive.ts. Scope is this product's domain (expense chat),
 * which is also why a full dictionary would need filtering, not just import.
 */

// --- pay verbs --------------------------------------------------------------

export interface PayVerbEntry {
  /** Surface stem, matched as a prefix INSIDE a hangul token. */
  stem: string
  /**
   * `verbal-noun` — a noun that is only a verb once a 하-suffix verbalizes it
   * (계산 → 계산했어). Backlog #2 lives here: a verbal noun followed by a
   * NOUN-forming suffix is still a noun, so 계산서 (the bill) and 계산기 (a
   * calculator) must never fire as pay-verbs.
   *
   * `verb-form` — already a verb: either an inflected form (냈, 샀, 긁었) or a
   * vowel-final stem that takes endings directly (쏘 → 쏠게/쏜다).
   *
   * NOT covered by either class: the PASSIVE 되-family (계산됐어, 결제됨,
   * 정산돼) — 됐/됨/돼 is neither a 하-verbalizer nor an ending, so those
   * sentences report no pay verb today. They are a real (if less common)
   * expense-chat shape; the fix is a 되-family entry alongside
   * `PAY_VERBALIZER`, deliberately deferred rather than smuggled into the
   * verbalizer list, where it would also accept 계산되기/계산될 nouns.
   */
  kind: 'verbal-noun' | 'verb-form'
  /**
   * The BARE form of this stem is a common word in its own right, so it is
   * held to two extra conditions: it must sit at the START of its token, and
   * its continuation must not be one of the swept collisions
   * (`AMBIGUOUS_STEM_COLLISIONS`). Its FUSED forms are unaffected.
   *
   * 내 is the case this exists for, and it collides three ways: on its own it
   * is the possessive "my" (내 잔액 / 내 지갑 / 내 몫); in the space-stripped
   * shadow text this parser also reads it starts ordinary nouns (내지갑 = 내 +
   * 지 + 갑, 내구성 = 내 + 구 + 성); and it is the tail of a family of
   * everyday verbs whose endings are real verb endings (끝내지, 티내네, 내게,
   * 방송내보내다니). Nothing about the SHAPE of those continuations separates
   * them from a payment — only the list does.
   *
   * Deliberately a per-entry FACT rather than a rule about stem length: 쏘 is
   * one syllable too and is not a word by itself, so it keeps the default.
   */
  ambiguous?: true
}

/**
 * Ordered longest-stem-first so a longer stem always wins at the same
 * position (사줬 before 샀 is not a real collision, but the ordering is the
 * invariant, asserted in the tests, not a coincidence of this content).
 */
export const PAY_VERB_ENTRIES: readonly PayVerbEntry[] = [
  { stem: '긁었', kind: 'verb-form' },
  { stem: '사줬', kind: 'verb-form' },
  { stem: '결제', kind: 'verbal-noun' },
  { stem: '계산', kind: 'verbal-noun' },
  { stem: '지불', kind: 'verbal-noun' },
  { stem: '냈', kind: 'verb-form' },
  { stem: '낸', kind: 'verb-form' },
  { stem: '냄', kind: 'verb-form' },
  { stem: '샀', kind: 'verb-form' },
  { stem: '쐈', kind: 'verb-form' },
  { stem: '쏘', kind: 'verb-form' },
  // The UNINFLECTED stem of 내다, added by the Task 11 corpus: 낼게 / 먼저
  // 낼게 / 내고 / 내자 are 상-frequency in the research file, and every one of
  // them was invisible while only the past forms 냈/낸/냄 were listed.
  // (내야지 is in that research row too and does NOT fire — 야 is not in
  // VERB_ENDING, so -아/어야지 forms were never reachable and are not what this
  // entry bought.)
  // ("민수가 먼저 낼게 5만원" credited the actor). `ambiguous` is what makes it
  // safe — see the field's own doc comment.
  { stem: '내', kind: 'verb-form', ambiguous: true },
  // 긁다's stem, for the same reason: 긁었 alone misses 긁음 / 긁고 / 긁는
  // (긁음 is attested 중). Listed AFTER 긁었 so the longer surface still wins
  // at the same position — the ordering invariant the tests assert.
  { stem: '긁', kind: 'verb-form' },
]

export const PAY_VERBS_KO: readonly string[] = PAY_VERB_ENTRIES.map((e) => e.stem)

/**
 * The 하-family verbalizers — the ONLY continuations that turn a verbal noun
 * into a verb: 계산했어/계산해/계산하고/계산한/계산할/계산함.
 *
 * This is the whitelist backlog #2 asks for, and it is a whitelist rather
 * than a 서/기 denylist on purpose: a noun-forming suffix inventory is open
 * (계산서/계산기/계산대/계산법/계산상/계산적…), while the verbalizer set is
 * closed at seven syllables.
 */
const VERBALIZER = ['하', '해', '했', '한', '할', '함', '합'] as const

/**
 * Endings that may follow an ALREADY-inflected pay-verb form. Each entry is
 * the ending's first syllable, so it covers everything built on it (`었` →
 * 었어/었다/었는데, `는` → 는데/는지, `게` → 게/게요).
 *
 * `으`/`을` carry the 으-mediated endings and the future attributive that the
 * regex this replaces also matched: 냈으니까/냈으면/냈으며, 냈을 때/냈을걸/
 * 사줬으면. They are safe to admit here because a VERBAL NOUN never consults
 * this list — it is held to `PAY_VERBALIZER` alone — so 계산서 cannot come
 * back in through 계산+을/으 or anything else.
 *
 * `서` is deliberately absent: no pay form needs a BARE 서 (the -아서/-어서
 * connective always shows its vowel first — 계산해서, 내서), and admitting it
 * would re-open 계산서 through the back door.
 */
const VERB_ENDING = [
  '어',
  '었',
  '아',
  '았',
  '으',
  '을',
  '다',
  '고',
  '는',
  '지',
  '네',
  '니',
  '나',
  '자',
  '요',
  '죠',
  '음',
  '게',
  '래',
  '겠',
  '더',
  '대',
  '거',
  '구',
  '잖',
  '습',
] as const

function anchoredAlternation(words: readonly string[]): RegExp {
  return new RegExp(`^(?:${words.join('|')})`)
}

/** Anchored: the text right after a VERBAL-NOUN pay stem must match this. */
export const PAY_VERBALIZER: RegExp = anchoredAlternation(VERBALIZER)

/** Anchored: the text right after an inflected pay-verb stem must match this. */
export const PAY_VERB_ENDING: RegExp = anchoredAlternation(VERB_ENDING)

const VERB_ENDING_SET: ReadonlySet<string> = new Set(VERB_ENDING)

/**
 * Continuations that make a BARE `ambiguous` stem an ordinary word rather than
 * a payment. Every one of them is a real Korean word starting with 내:
 *
 *   내게 (to me)      내음 (a scent)     내구 (durability)   내거 (mine)
 *   내습 (an assault) 내대 (a stand)     내나 / 내래 / 내아 / 내을 / 내어
 *   내지 / 내네
 *
 * This is a CLOSED set, swept rather than guessed: every pure-hangul surface
 * in mecab-ko-dic's NNG/MAG/NNP/VV/VA/IC/MM seed files (229,923 words) was
 * tested for "내 + a continuation that is entirely verb-ending material", and
 * these are the collisions that occur with 내 at the START of the word. The
 * collisions that occur INSIDE a longer word (안내자, 안내대, 끝내어, 끝내지,
 * 티내네, 제내지, 방송내보내다니) are not on this list because a continuation
 * cannot separate them — 내자 "let's pay" and 안내자 "a guide" have the SAME
 * continuation — so they are handled by the position rule instead: an
 * `ambiguous` stem only matches at the START of a token (parsers/split.ts).
 *
 * Everything else that is ending material still fires, which is the point of
 * the inversion: 내겠어 / 내겠다 / 내죠 / 내잖아 / 내고 / 내자 / 내는 / 내요 /
 * 내다 / 내다니 are all payments and all resolve their payer.
 */
const AMBIGUOUS_STEM_COLLISION_WORDS: readonly string[] = [
  '어', '게', '음', '구', '거', '습', '대', '나', '래', '아', '을', '지', '네',
]

/**
 * The collisions above, each ALSO with every particle that can ride on it.
 *
 * Every collision is a NOUN (내게 "to me", 내음 "a scent", 내거 "mine"), and a
 * noun takes josa — so 내게는 / 내거는 / 내구는 / 내게나 are the same words
 * wearing a particle, and exact-matching the bare form let all of them through
 * as pay verbs (fix round 3). A VERB ENDING is not a josa, which is exactly
 * why this is generated from `JOSA` rather than done as a prefix match: 내네요
 * and 내지요 START with a collision (네, 지) and are ordinary polite verb
 * forms, so a prefix rule would silence them too.
 *
 * The product is small by construction: `isAmbiguousStemEnding` has already
 * required the whole continuation to be verb-ending material, and only 나 / 는
 * / 을 of the mined 43-josa inventory are made of ending syllables — every
 * other particle (이/가/도/만/에/를/…) is refused one step earlier.
 */
const AMBIGUOUS_STEM_COLLISIONS: ReadonlySet<string> = new Set([
  ...AMBIGUOUS_STEM_COLLISION_WORDS,
  ...AMBIGUOUS_STEM_COLLISION_WORDS.flatMap((word) => JOSA.map((josa) => word + josa)),
])

/**
 * Whether `rest` is a legal continuation for a BARE `ambiguous` stem: entirely
 * verb-ending material (which is what keeps 내지갑 / 내구성 out — 갑 and 성
 * are not endings), and not one of the swept collisions above.
 */
export function isAmbiguousStemEnding(rest: string): boolean {
  if (rest === '') return false
  if (AMBIGUOUS_STEM_COLLISIONS.has(rest)) return false
  return [...rest].every((syllable) => VERB_ENDING_SET.has(syllable))
}

/**
 * The verbalizing-suffix whitelist of the brief: a pay stem counts only when
 * what follows it is one of these, or nothing at all (end of the word).
 *
 * It is the UNION of the two class-specific whitelists above; matching it is
 * necessary for every stem, and SUFFICIENT only for the `verb-form` class —
 * a `verbal-noun` stem is additionally held to `PAY_VERBALIZER`, which is
 * what keeps 계산서/계산기 from firing (backlog #2). `findPayVerbs`
 * (parsers/split.ts) applies exactly that rule.
 */
export const PAY_VERB_SUFFIX: RegExp = anchoredAlternation([...VERBALIZER, ...VERB_ENDING])

// --- split expressions ------------------------------------------------------

/**
 * Korean split vocabulary. Matched against the RAW INPUT (not per token), so
 * a spaced variant is its own entry ("다 같이") rather than a whitespace
 * pattern — an entry is exactly the text it matches, which is what lets every
 * hit carry an exact span (backlog #5: only spans an actual hit consumed are
 * ever removed from the description; there is no global NOISE sweep).
 *
 * Hangul has no \b, so these fire on substrings in principle. 엔빵/다같이/
 * 모두/전부/나눠/나누자/반반/절반 are specific enough that a false hit inside
 * another word is not a realistic concern — the same judgement index.ts's
 * EVERYONE regex has always made, deliberately preserved here.
 *
 * Deliberately NOT included: bare 같이 (product ruling, coordinator
 * 2026-08-09). It adds nothing when no member is named — participants already
 * default to everyone in that case — and it actively misreads a restriction
 * when a member IS named: "민수랑 같이 저녁 3만원" means "with Minsu" (a
 * two-person split), not "with Minsu, everyone". A standalone "다같이" still
 * means everyone and is unaffected.
 */
export const SPLIT_ENTRIES_KO: readonly SplitEntry[] = [
  { text: '엔빵', mode: 'everyone', confidence: 1 },
  { text: 'n빵', mode: 'everyone', confidence: 1 },
  { text: 'N빵', mode: 'everyone', confidence: 1 },
  { text: '다같이', mode: 'everyone', confidence: 1 },
  { text: '다 같이', mode: 'everyone', confidence: 1 },
  { text: '모두', mode: 'everyone', confidence: 1 },
  { text: '전부', mode: 'everyone', confidence: 1 },
  // 나눠 is the plain converb of 나누다 ("dividing"), not a word for the whole
  // group: "지훈이랑 나눠냈어" divides between the two people it names, while
  // "다같이 나눠서" carries its own everyone-word. Sub-full confidence is how
  // that uncertainty is stated — the same treatment English `each` gets, and
  // the same ruling bare 같이 already got (index.test.ts, 2026-08-09 review):
  // with a member NAMED, a divide-word restricts rather than including
  // everybody. 나누자 keeps full confidence: it is a request to split, with no
  // second reading.
  { text: '나눠', mode: 'everyone', confidence: 0.6 },
  { text: '나누자', mode: 'everyone', confidence: 1 },
  { text: '반반', mode: 'half', confidence: 1 },
  { text: '절반', mode: 'half', confidence: 1 },
]

export const SPLIT_KO: readonly string[] = SPLIT_ENTRIES_KO.map((e) => e.text)

// --- clause-forming verbs and adjectives ------------------------------------

/**
 * 하다-VERB roots: root + 하 is the stem, so 추천하 → 추천한/추천해서/추천하고.
 * Their attributive form is a clause boundary — "유나가 추천한 식당에서 …
 * 냈어" has 유나 as the subject of an EMBEDDED clause, not of the pay verb.
 */
export const HADA_VERB_ROOTS: readonly string[] = [
  '추천',
  '예약',
  '주문',
  '결제',
  '계산',
  '지불',
  '정산',
  '구매',
  '구입',
  '배달',
  '초대',
  '준비',
  '취소',
  '예매',
  '방문',
  '사용',
  '송금',
  '이체',
  '환불',
  '식사',
]

/**
 * Non-하다 verb stems, in dictionary-stem form (no 다).
 *
 * Scoped to expense chat, and deliberately excluding stems whose attributive
 * form collides with a common noun — 가다→간 (간/간장), 보다→본, 타다→탄,
 * 걷다 (ㄷ-irregular: 걷+은 → 걸은, which this grammar does not model). A
 * missing stem costs a clause boundary (the SAFE direction: the embedded
 * subject keeps the payer role, visible and correctable on the confirm card);
 * a colliding one costs a wrong ACTOR fallback, which is the direction
 * docs/SOLVED.md's Task 4 rounds repeatedly punished.
 */
export const PLAIN_VERB_STEMS_KO: readonly string[] = [
  '먹',
  '사',
  '사주',
  '마시',
  '시키',
  '고르',
  '만들',
  '나누',
  '빌리',
  '갚',
  '받',
  // 보내다 (send) — a money verb in its own right (송금), and the stem that
  // lets ko/attributive.ts read 보낸/보내는 as SOMEONE ELSE'S clause instead of
  // letting the pay stem 낸 fire inside it ("유나가 보낸 돈 민수가 냈어" — the
  // payer is 민수, and 보낸 is the boundary that says so).
  '보내',
  '긁',
  '쏘',
  '내',
]

export const VERB_STEMS_KO: readonly string[] = [
  ...PLAIN_VERB_STEMS_KO,
  ...HADA_VERB_ROOTS.map((root) => `${root}하`),
]

/**
 * 하다-ADJECTIVE roots — the dominant OVER-flagging class Task 4's fix round 4
 * identified: X한 modifies the FOLLOWING noun and never displaces the
 * subject, so "유나가 시원한 맥주 샀어" must credit 유나, not the actor.
 * Their attributive forms are exactly the shape (2+ syllables, ending 한) a
 * literal ending set cannot tell apart from 추천한 — only the stem's class
 * can, which is why both tables exist.
 */
export const HADA_ADJ_ROOTS: readonly string[] = [
  '유명',
  '저렴',
  '시원',
  '간단',
  '따뜻',
  '조용',
  '깔끔',
  '특별',
  '다양',
  '이상',
  '신선',
  '훌륭',
  '근사',
  '적당',
  '화려',
  '매콤',
  '달콤',
  '얼큰',
  '담백',
  '고소',
  '상큼',
  '푸짐',
  '비슷',
  '안전',
  '충분',
  '확실',
  '필요',
  '중요',
  '유용',
  '편안',
  '친절',
  '불편',
  '피곤',
  '한가',
  '심심',
  '편',
  '착',
  '급',
]

/**
 * Non-하다 adjective stems.
 *
 * ㅂ-irregular adjectives (맵다→매운, 귀엽다→귀여운, 새롭다→새로운, 어렵다→
 * 어려운) are deliberately absent: this grammar does not model the ㅂ→우
 * alternation, and a regular ㅂ-final adjective exists too (좁다→좁은), so
 * guessing per stem would produce wrong surfaces. Omitting them costs an
 * adjective recognition (which only means "no opinion"), never a wrong one.
 */
export const PLAIN_ADJ_STEMS_KO: readonly string[] = [
  '좋',
  '많',
  '적',
  '크',
  '작',
  '비싸',
  '싸',
  '맛있',
  '맛없',
  '재밌',
  '재미있',
  '예쁘',
  '나쁘',
  '어리',
  '괜찮',
  '배부르',
  '배고프',
]

export const ADJ_STEMS_KO: readonly string[] = [
  ...PLAIN_ADJ_STEMS_KO,
  ...HADA_ADJ_ROOTS.map((root) => `${root}하`),
]
